import type { Metadata } from "next";
import "./globals.css";
import NabBar from "@/components/UI/NabBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NabBar />
        <div className="px-4 m-auto">{children}</div>
      </body>
    </html>
  );
}
